variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "ssh_public_key_file_bastion" {}
variable "ssh_private_key_file_bastion" {}
variable "ssh_public_key_file_private" {}
variable "ssh_private_key_file_private" {}
variable "cidr_vcn" {}
variable "cidr_public_subnet" {}
variable "cidr_private_subnet" {}
variable "inst_shape" {}
variable "inst_image" {}
variable "http_proxy" {}
variable "mount_point" {}
variable "cloudinit_script_bastion" {}
variable "cloudinit_script_private" {}
