variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "ssh_public_key_file" {}
variable "ssh_private_key_file" {}
variable "inst_image" {}
variable "http_proxy" {}
variable "cidr_vcn" {}
variable "cidr_public_subnet" {}
variable "cidr_private_subnet" {}
variable "number_of_instances" {}
variable "instances_name" {}
variable "instances_hostname" {}
variable "instances_shape" {}
variable "instances_post_prov" {}
